#!/bin/bash

TIMESTAMP=$(date +%Y-%m-%d)
BACKUPFILE=gogs-backup-$TIMESTAMP.tar.gz
echo "Backing up to $BACKUPFILE"
docker run --rm -t -v gogs_data:/data -v $PWD:/backup alpine:latest tar czvf /backup/$BACKUPFILE /data
smbclient //powerman/public -D backups -N -U anonymous -c 'put $BACKUPFILE'
